### ISSUE TITLE
How to run this code ?

### ISSUE THREAD

**Issue by rsingh2083** [ankit1khare/Smart-Park-with-YOLO-V3#1]
Hi Ankit,

Awesome work buddy !!
Can you pls help me with running this code on the video files ?
I mean which file to run and what parameters to pass ?
A readme would definitely hep

**Comment by Shubammanhas** [comment]
I am facing the same issue. He has not mentioned in Readme as well. Have you found any solution ?

**Comment by ankit1khare** [comment]
yolo_park jupyter notebook is the one you are looking for.

**Comment by buraksarikatipoglu** [comment]
> yolo_park jupyter notebook is the one you are looking for.

Hello, 
If I can run this code, everything would be perfect. What do you mean by ''yolo_park jupyter notebook is the one you are looking for.'' ? May I ask you to direct me to some link or anywhere :D Thank you very much

Best Regards,
